import type { TimelineMilestone } from "../types";

export const TIMELINE_MILESTONES: TimelineMilestone[] = [
  {
    id: "gemma-1",
    name: "Gemma 1",
    date: "Feb 2024",
    family: "gemma",
    description:
      "Google DeepMind's first open-weights model family. Lightweight 2B & 7B text models.",
    highlight: "The beginning of open Gemma",
    modelIds: [],
    blogUrl: "https://ai.google.dev/gemma/docs/core/model_card",
  },
  {
    id: "recurrentgemma",
    name: "RecurrentGemma",
    date: "Apr 2024",
    family: "recurrent",
    description:
      "Google's first RNN-based Gemma. Handles long sequences efficiently using recurrent layers instead of full attention.",
    highlight: "Recurrence over attention",
    modelIds: [],
    blogUrl: "https://deepmind.google/models/gemma/recurrentgemma/",
  },
  {
    id: "codegemma",
    name: "CodeGemma",
    date: "Apr 2024",
    family: "code",
    description:
      "Code-focused Gemma trained on 500B+ tokens of code. Supports code completion, generation, and infilling across 10+ languages.",
    highlight: "500B+ code tokens",
    modelIds: [],
    blogUrl: "https://ai.google.dev/gemma/docs/codegemma",
  },
  {
    id: "paligemma-1",
    name: "PaliGemma",
    date: "May 2024",
    family: "paligemma",
    description:
      "Vision-language model combining SigLIP + Gemma. Capable of image captioning, VQA, and OCR.",
    highlight: "Gemma goes multimodal",
    modelIds: [],
    blogUrl: "https://ai.google.dev/gemma/docs/paligemma",
  },
  {
    id: "gemini-nano",
    name: "Gemini Nano",
    date: "May 2024",
    family: "nano",
    description:
      "Google's on-device AI model built directly into Chrome. No model download — powered by Chrome's Prompt API (window.ai). The first browser-native LLM shipped at OS level.",
    highlight: "Built into Chrome",
    modelIds: ["gemini-nano"],
    blogUrl: "https://developer.chrome.com/docs/ai",
    mediaUrl: "https://www.youtube.com/embed/CjpZCWYrSxM",
    isSpecial: true,
  },
  {
    id: "gemma-2",
    name: "Gemma 2",
    date: "Jun 2024",
    family: "gemma2",
    description:
      "Major architecture improvements: sliding window attention, logit soft-capping, and grouped-query attention.",
    highlight: "2× efficiency gains",
    modelIds: [],
    blogUrl: "https://ai.google.dev/gemma/docs/core/model_card_2",
  },
  {
    id: "shieldgemma",
    name: "ShieldGemma",
    date: "Jul 2024",
    family: "shield",
    description:
      "Safety classifier built on Gemma. Evaluates text for harm categories including dangerous content, hate speech, and sexual content.",
    highlight: "On-device safety filtering",
    modelIds: [],
    blogUrl: "https://ai.google.dev/gemma/docs/shieldgemma",
  },
  {
    id: "datagemma",
    name: "DataGemma",
    date: "Sep 2024",
    family: "data",
    description:
      "Grounds language model responses in real-world statistical data via Google's Data Commons knowledge graph.",
    highlight: "Grounded in real-world data",
    modelIds: [],
    blogUrl: "https://ai.google.dev/gemma/docs/datagemma",
  },
  {
    id: "paligemma-2",
    name: "PaliGemma 2",
    date: "Dec 2024",
    family: "paligemma",
    description:
      "Upgraded vision-language model on the Gemma 2 backbone with support for higher resolutions and stronger visual understanding.",
    highlight: "Better vision + Gemma 2",
    modelIds: [],
    blogUrl: "https://ai.google.dev/gemma/docs/paligemma2",
  },
  {
    id: "gemma-3",
    name: "Gemma 3",
    date: "Feb 2025",
    family: "gemma3",
    description:
      "New 270M to 27B range, context window up to 128k tokens, multilingual by default.",
    highlight: "128k context",
    modelIds: ["gemma-3-270m-it", "gemma-3-1b-it"],
  },
  {
    id: "paligemma-2-mix",
    name: "PaliGemma 2 Mix",
    date: "Feb 2025",
    family: "paligemma",
    description:
      "PaliGemma 2 fine-tuned on a mixture of tasks: captioning, VQA, object detection, and more. Available at 224px resolution.",
    highlight: "Multi-task fine-tune",
    modelIds: ["paligemma2-3b-mix-224"],
  },
  {
    id: "shieldgemma-2",
    name: "ShieldGemma 2",
    date: "Mar 2025",
    family: "shield",
    description:
      "Improved safety classifier supporting both image and text inputs. Evaluates multimodal content for policy violations at 256px resolution.",
    highlight: "Multimodal safety",
    modelIds: [],
    blogUrl: "https://ai.google.dev/gemma/docs/shieldgemma/model_card_2",
  },
  {
    id: "dolphingemma",
    name: "DolphinGemma",
    date: "Apr 2025",
    family: "dolphin",
    description:
      "Gemma fine-tuned on 40 years of dolphin vocalisation data from the Wild Dolphin Project. The first AI model to study dolphin communication.",
    highlight: "Speaks dolphin",
    modelIds: [],
    blogUrl: "https://blog.google/innovation-and-ai/products/dolphingemma/",
    mediaUrl: "https://www.youtube.com/embed/jH98kvC9f1s",
  },
  {
    id: "medgemma",
    name: "MedGemma",
    date: "May 2025",
    family: "med",
    description:
      "Medical AI model fine-tuned on biomedical text, radiology reports, and medical images. Designed for healthcare developers.",
    highlight: "Biomedical reasoning",
    modelIds: [],
    blogUrl: "https://developers.google.com/health-ai-developer-foundations/medgemma",
  },
  {
    id: "gemma-3n",
    name: "Gemma 3n",
    date: "Jun 2025",
    family: "gemma3n",
    description:
      "New architecture optimised for on-device inference. E2B has an effective 2B parameter footprint with native multimodal support.",
    highlight: "On-device multimodal",
    modelIds: ["gemma-3n-e2b-it"],
  },
  {
    id: "t5gemma",
    name: "T5Gemma",
    date: "Jul 2025",
    family: "t5",
    description:
      "Encoder-decoder Gemma combining T5's seq2seq strengths with Gemma's generation quality. Excels at summarisation and translation.",
    highlight: "Encoder + Decoder",
    modelIds: [],
    blogUrl: "https://developers.googleblog.com/en/t5gemma/",
  },
  {
    id: "embeddinggemma",
    name: "EmbeddingGemma",
    date: "Sep 2025",
    family: "embedding",
    description:
      "300M-parameter text embedding model built on Gemma 3. Produces dense vectors for search, retrieval, and semantic similarity across 100+ languages.",
    highlight: "Text to Vectors",
    modelIds: ["embeddinggemma-300m"],
  },
  {
    id: "vaultgemma",
    name: "VaultGemma",
    date: "Sep 2025",
    family: "vault",
    description:
      "Privacy-preserving text generation trained with Differential Privacy (ε≤2, DP-SGD). Safe for deployment on sensitive healthcare and finance data.",
    highlight: "Differential Privacy ε≤2",
    modelIds: ["vaultgemma-1b"],
    blogUrl: "https://huggingface.co/google/vaultgemma-1b",
  },
  {
    id: "functiongemma",
    name: "FunctionGemma",
    date: "Dec 2025",
    family: "function",
    description:
      "270M function-calling model that generates structured tool invocations from natural language. Built for agentic pipelines and API orchestration.",
    highlight: "Structured tool use",
    modelIds: ["functiongemma-270m-it"],
    blogUrl: "https://huggingface.co/google/functiongemma-270m-it",
  },
  {
    id: "t5gemma-v2",
    name: "T5Gemma v2",
    date: "Dec 2025",
    family: "t5",
    description:
      "Second generation T5Gemma with improved seq2seq quality, extended task coverage, and better multilingual performance.",
    highlight: "Improved seq2seq",
    modelIds: [],
    blogUrl: "https://blog.google/innovation-and-ai/technology/developers-tools/t5gemma-2/",
  },
  {
    id: "translategemma",
    name: "TranslateGemma",
    date: "Jan 2026",
    family: "translate",
    description:
      "4B-parameter translation model built on Gemma. Translates between 100+ languages fully on-device via WebGPU.",
    highlight: "100+ language translation",
    modelIds: ["translategemma-4b"],
  },
  {
    id: "gemma-4",
    name: "Gemma 4",
    date: "Apr 2026",
    family: "gemma4",
    description:
      "First Gemma to natively process text, image, and audio in a single model. MoE architecture.",
    highlight: "Audio + Image + Text",
    modelIds: ["gemma-4-e2b-it"],
  },
  {
    id: "diffusiongemma",
    name: "DiffusionGemma",
    date: "Jun 2026",
    family: "diffusion",
    description:
      "Diffusion-based language model built on Gemma. Generates text by iteratively denoising masked tokens, enabling faster parallel decoding compared to autoregressive approaches.",
    highlight: "Parallel token generation",
    modelIds: [],
    blogUrl: "https://blog.google/innovation-and-ai/technology/developers-tools/diffusion-gemma-faster-text-generation/",
  },
];

export const FAMILY_COLORS: Record<string, string> = {
  gemma:     "#0ea5e9",
  gemma2:    "#6366f1",
  gemma3:    "#14b8a6",
  gemma3n:   "#06b6d4",
  gemma4:    "#f59e0b",
  paligemma: "#ec4899",
  embedding: "#84cc16",
  translate: "#a855f7",
  recurrent: "#f97316",
  code:      "#22c55e",
  shield:    "#ef4444",
  data:      "#d946ef",
  dolphin:   "#38bdf8",
  med:       "#fb923c",
  vault:     "#2dd4bf",
  t5:        "#8b5cf6",
  function:  "#eab308",
  diffusion: "#f43f5e",
  nano:      "#4285f4",
};
